
kind: Namespace
apiVersion: v1
metadata:
  name: my-cloud

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-center
  namespace: my-cloud
  labels:
    app: service-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-center
  template:
    metadata:
      labels:
        app: service-center
    spec:
      containers:
        - name: service-center
          image: service_center:latest
          #command: ["/bin/sh","-c","java -Xmx800m -Xms800m -Xmn300m -Djava.security.egd=file:/dev/./urandom -jar
          #/app.jar --spring.profiles.active=$ENV"]
          command: ["/bin/sh","-c","java -Xmx800m -Xms800m -Xmn300m -Djava.security.egd=file:/dev/./urandom -jar /app.jar"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9900
              name: port-9900

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-center
  name: service-center
  namespace: my-cloud
spec:
  ports:
    - port: 9900
      name: port-9900
      protocol: TCP
      targetPort: 9900
  selector:
    app: service-center
  externalIPs:
    - 192.168.1.220