server:
  port: ${PORT:9900}

spring:
  application:
    name: my_eureka
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASSWORD:ad2020min}


eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: 注册中心(${spring.cloud.client.ip-address}:${server.port})
  server:
    responseCacheUpdateInvervalMs: 3000
    responseCacheAutoExpirationInSeconds: 180
    eviction-interval-timer-in-ms: 3000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
