server:
  port: ${PORT:9900}

spring:
  application:
    name: my_eureka
  security:
    basic:
      enable: true #开启基于HTTP basic的认证
    user: #配置用户的账号信息
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASSWORD:ad2020min}


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
